import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '../components/theme-provider'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Providers wrap around our applicationn and give them access to data.
// NextThemesProvider - Gives us access to light / dark mode data.
// Providers are generally on the cliennt side ("use client")
// Switch from light mode to dark mode <-- user interaction / needs the client to exist.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme="dark">
            <main className="flex min-h-screen flex-col items-center p-24">
              <div className="z-10 max-w-5xl w-full items-center justify-between text-sm lg:flex">
               <Link href="/"><h1 className='text-xl font-bold'>PokmonFinder</h1></Link>   
              </div>
         {children}
            </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
